import { Link } from "react-router-dom";
import { radarErrorMessage } from "../../utils/opportunityRadarClient.js";

export default function RadarFeedback({ status, error, lang, filter = "all", reload, compact = false }) {
  const tr = lang === "TR";
  if (status === "loading") return <div className="hf-radar-feedback" role="status"><p>{tr ? "Sana uygun iş ve staj fırsatları hazırlanıyor…" : "Preparing your job and internship opportunities…"}</p><div className="hf-radar-skeleton" aria-hidden="true" /></div>;
  if (status === "profile_required") return <div className="hf-radar-feedback"><h3>{tr ? "Kariyer hafızanla başlayalım" : "Start with your Career Memory"}</h3><p>{tr ? "Kişiselleştirilmiş eşleştirme için kariyer profilini oluştur. Bilgilerini burada yeniden istemiyoruz." : "Create your career profile for personalized matching. You do not need to enter it again here."}</p><Link className="hf-btn-secondary" to="/career-dna">{tr ? "Kariyer profiline git" : "Go to Career Profile"}</Link></div>;
  if (status === "error") return <div className="hf-radar-feedback"><p role="alert">{radarErrorMessage(error, lang)}</p>{error?.code === "AUTH_REQUIRED" ? <Link className="hf-btn-secondary" to="/login?next=%2Fopportunity-radar">{tr ? "Giriş yap" : "Sign in"}</Link> : <button type="button" className="hf-btn-secondary" onClick={reload}>{tr ? "Tekrar dene" : "Retry"}</button>}</div>;
  return <div className="hf-radar-feedback" role="status"><h3>{filter === "saved" ? (tr ? "Henüz aktif bir kayıtlı fırsat yok" : "No active saved opportunities yet") : (tr ? "Şu anda gösterilecek doğrulanmış fırsat yok" : "No verified opportunities to show right now")}</h3><p>{filter === "saved" ? (tr ? "Tümü listesinden ilgini çeken fırsatları kaydedebilirsin. Süresi dolan fırsatlar gösterilmez." : "Save opportunities from All. Expired opportunities are not shown.") : (tr ? "Bu, profilinin yetersiz olduğu anlamına gelmez. Yalnızca doğrulanmış ve güncel ilanları gösteriyoruz." : "This does not reflect your profile quality. Only verified, current listings are shown.")}</p>{!compact && <button type="button" className="hf-btn-secondary" onClick={reload}>{tr ? "Listeyi yenile" : "Refresh list"}</button>}</div>;
}
