import { getUserFromRequest } from "../auth/verifySupabaseJwt.js";
import { loadCareerProfile } from "../careerMemory/persistence.js";
import { generatePromotionRaiseGuidance, PROMOTION_RAISE_PROMPT_VERSION } from "./aiGuidance.js";
import { deleteCase, getCase, listCases, saveCase, saveOutcome } from "./persistence.js";
import { normalizeCaseInput, validateOutcome } from "./validation.js";
function json(res, status, body) { res.status(status).json(body); }
async function auth(req, res) { const a = await getUserFromRequest(req); if (!a.ok) { json(res, a.status, { success: false, error: "AUTH_REQUIRED" }); return null; } req.authUser = a.user; return a.user; }
export function registerCareerCompanionRoutes(app) {
  app.get("/api/career-companion/cases", async (req, res) => { const u = await auth(req, res); if (!u) return; try { json(res, 200, { success: true, cases: await listCases(u.id) }); } catch { json(res, 503, { success: false, error: "STORAGE_UNAVAILABLE" }); } });
  app.get("/api/career-companion/cases/:id", async (req, res) => { const u = await auth(req, res); if (!u) return; try { const item = await getCase(u.id, req.params.id); if (!item) return json(res, 404, { success: false, error: "NOT_FOUND" }); json(res, 200, { success: true, case: item }); } catch { json(res, 503, { success: false, error: "STORAGE_UNAVAILABLE" }); } });
  app.post("/api/career-companion/cases", async (req, res) => { const u = await auth(req, res); if (!u) return; const normalized = normalizeCaseInput(req.body || {}); if (!normalized.ok) return json(res, 400, { success: false, error: "INVALID_INPUT", fields: normalized.errors }); try { const item = await saveCase(u.id, normalized.value); json(res, 201, { success: true, case: item }); } catch { json(res, 503, { success: false, error: "STORAGE_UNAVAILABLE" }); } });
  app.delete("/api/career-companion/cases/:id", async (req, res) => { const u = await auth(req, res); if (!u) return; try { await deleteCase(u.id, req.params.id); json(res, 200, { success: true }); } catch (e) { json(res, e.code === "CASE_NOT_FOUND_OR_NOT_OWNED" ? 404 : e.code === "CASE_NOT_DRAFT" ? 409 : 503, { success: false, error: e.code || "STORAGE_UNAVAILABLE" }); } });
  app.post("/api/career-companion/cases/:id/guidance", async (req, res) => { const u = await auth(req, res); if (!u) return; try { const item = await getCase(u.id, req.params.id); if (!item) return json(res, 404, { success: false, error: "NOT_FOUND" }); const profile = await loadCareerProfile(u.id); const guidance = await generatePromotionRaiseGuidance({ input: item, profile, lang: req.body?.lang || "TR" }); const saved = await saveCase(u.id, { id: item.id, guidance, guidance_model: process.env.ANTHROPIC_MODEL || "claude-haiku-4-5-20251001", guidance_prompt_version: PROMOTION_RAISE_PROMPT_VERSION, status: "guided" }); json(res, 200, { success: true, case: saved }); } catch (e) { json(res, e.code === "CASE_NOT_FOUND_OR_NOT_OWNED" ? 404 : e.code === "MALFORMED_GUIDANCE_OUTPUT" ? 502 : 503, { success: false, error: e.code || "GUIDANCE_UNAVAILABLE" }); } });
  app.post("/api/career-companion/cases/:id/outcome", async (req, res) => { const u = await auth(req, res); if (!u) return; const check = validateOutcome(req.body || {}); if (!check.ok) return json(res, 400, { success: false, error: "INVALID_OUTCOME" }); try { if (!await getCase(u.id, req.params.id)) return json(res, 404, { success: false, error: "NOT_FOUND" }); json(res, 200, { success: true, outcome: await saveOutcome(u.id, req.params.id, { manager_response: String(req.body.manager_response).trim(), measurable_effect: String(req.body.measurable_effect || "").trim(), proof_reference: String(req.body.proof_reference || "").trim(), outcome_date: req.body.outcome_date || null }) }); } catch (e) { json(res, e.code === "CASE_NOT_FOUND_OR_NOT_OWNED" ? 404 : 503, { success: false, error: e.code || "STORAGE_UNAVAILABLE" }); } });
}
