export const INTELLIGENCE_ENGINE_VERSION = "decision-intelligence.5.5a";
export const EVIDENCE_SCHEMA_VERSION = "evidence.v1";
export const REASONING_REPORT_SCHEMA_VERSION = "reasoning-report.v1";
export const DECISION_OPTION_SCHEMA_VERSION = "decision-option.v1";
export const SHADOW_SUMMARY_SCHEMA_VERSION = "shadow-summary.v1";
export const ACTIVATION_POLICY_VERSION = "activation-policy.v1";

export default {
  INTELLIGENCE_ENGINE_VERSION,
  EVIDENCE_SCHEMA_VERSION,
  REASONING_REPORT_SCHEMA_VERSION,
  DECISION_OPTION_SCHEMA_VERSION,
  SHADOW_SUMMARY_SCHEMA_VERSION,
  ACTIVATION_POLICY_VERSION,
};
